name: Terraform

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
      - name: Init Terraform
        run: terraform init
    - name: Apply Terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}






