name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
      - name: Set up AWS credentials
        run: echo "$AWS_ACCESS_KEY_ID" > ~/.aws/credentials
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}
      - name: Init Terraform
        run: terraform init
      - name: Apply Terraform
        run: terraform apply -auto-approve
         
      - name: Destroy Terraform
        run: terraform destroy -auto-approve






